import React from 'react';
import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUpRight,
  IconBell,
  IconBold,
  IconBooks,
  IconBox,
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandTiktok,
  IconBrandTwitter,
  IconBrightness,
  IconBuilding,
  IconBuildingSkyscraper,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconHeart,
  IconCircle,
  IconCircleCheck,
  IconCircleDashed,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCoin,
  IconCommand,
  IconCopy,
  IconCreditCard,
  IconDeviceFloppy,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileDescription,
  IconFileText,
  IconFileTypeDoc,
  IconFileTypePdf,
  IconFileTypeXls,
  IconFileZip,
  IconFlame,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconHistory,
  IconHome,
  IconInfoCircle,
  IconInbox,
  IconItalic,
  IconKey,
  IconLayersLinked,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLink,
  IconListCheck,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMessage2,
  IconMapPin,
  IconMinus,
  IconMoon,
  IconMovie,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPercentage,
  IconPhone,
  IconPhoto,
  IconPlayerPlay,
  IconPlus,
  IconPointer,
  IconProps,
  IconRefresh,
  IconRobot,
  IconRocket,
  IconRosetteDiscountCheck,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconShield,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconTag,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserCircle,
  IconUserEdit,
  IconUserPlus,
  IconUserX,
  IconUsers,
  IconVideo,
  IconCrown,
  IconX,
  IconBolt,
  IconBriefcase,
  IconApps,
  IconThumbUp,
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  arrowLeft: IconArrowLeft,
  arrowUpRight: IconArrowUpRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  copy: IconCopy,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  refresh: IconRefresh,
  history: IconHistory,
  activity: IconActivity,
  chartBar: IconChartBar,
  shield: IconShield,
  bell: IconBell,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  home: IconHome,
  building: IconBuilding,
  key: IconKey,
  bot: IconRobot,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand & Social
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  instagram: IconBrandInstagram,
  tiktok: IconBrandTiktok,
  logo: IconCommand,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,
  mail: IconSend,

  // Files
  page: IconFile,
  post: IconFileText,
  fileText: IconFileText,
  document: IconFileDescription,
  fileEdit: IconFileDescription,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  download: IconDownload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Data / Charts
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  barChart: IconChartBar,
  layers: IconStack2,
  eyeOff: IconEyeOff,
  eye: IconEye,
  adjustments: IconAdjustmentsHorizontal,
  mousePointer: IconPointer,
  percent: IconPercentage,
  flame: IconFlame,
  workflow: IconLayoutKanban,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  workspace: IconFolder,
  location: IconMapPin,
  mapPin: IconMapPin,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  moreHorizontal: IconDots,
  galleryVerticalEnd: IconStack2,

  // Extended — added for full icon-registry migration
  rocket: IconRocket,
  userCheck: IconUserCheck,
  userPlus: IconUserPlus,
  messageSquare: IconMessage2,
  playCircle: IconPlayerPlay,
  play: IconPlayerPlay,
  listChecks: IconListCheck,
  tag: IconTag,
  banknote: IconCoin,
  inbox: IconInbox,
  clapperboard: IconMovie,
  circleDashed: IconCircleDashed,
  link: IconLink,
  pencil: IconPencil,
  save: IconDeviceFloppy,
  building2: IconBuildingSkyscraper,
  layers2: IconLayersLinked,
  bookOpen: IconBooks,
  keyRound: IconKey,

  // Reference-specific mappings (Luminous Space admin)
  // NOTE: add/dashboard/help/search/send/settings already exist above.
  add_circle: IconCirclePlus,
  apps: IconApps,
  arrow_forward: IconArrowRight,
  auto_awesome: IconSparkles,
  bolt: IconBolt,
  business: IconBuildingSkyscraper,
  calendar_month: IconCalendar,
  campaign: IconRocket,
  hub: IconLayersLinked,
  ios_share: IconShare,
  monitoring: IconChartBar,
  more_vert: IconDotsVertical,
  music_note: IconMusic,
  notifications: IconBell,
  photo_camera: IconPhoto,
  schedule: IconClock,
  smart_display: IconVideo,
  thumb_up: IconThumbUp,
  trending_up: IconTrendingUp,
  work: IconBriefcase,
  zap: IconBolt,
  heart: IconHeart,
};

