/**
 * Brand Profile Markdown Parser & Serializer
 * Parses the exact markdown format generated by AI into a structured TypeScript object
 * and serializes it back to markdown for storage.
 */

export interface BrandPillar {
  name: string
  description: string
  percentage: number
}

export interface BrandProfileData {
  clientName: string
  whoWeAre: string
  audiencePersona: string
  voice: {
    tone: string[]
    dos: string[]
    donts: string[]
  }
  pillars: BrandPillar[]
  channels: string[]
  brandAssets: string[]
}

export const SECTION_HEADERS = [
  'Who We Are',
  'Audience Persona',
  'Voice & Guardrails',
  'Content Pillars',
  'Channels (Active Platforms)',
  'Brand Assets Needed',
] as const

function extractSection(content: string, header: string): string {
  const escaped = header.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  // No `m` flag: `$` must mean end-of-string, not end-of-line, or the lazy
  // match stops at the first newline and every section parses as one line.
  const regex = new RegExp(`## ${escaped}\\n([\\s\\S]*?)(?=\\n## |$)`)
  const match = content.match(regex)
  return match?.[1]?.trim() ?? ''
}

function extractSubSection(content: string, parentHeader: string, subHeader: string): string {
  const parentContent = extractSection(content, parentHeader)
  const escaped = subHeader.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const regex = new RegExp(`### ${escaped}\\n([\\s\\S]*?)(?=\\n### |$)`)
  const match = parentContent.match(regex)
  return match?.[1]?.trim() ?? ''
}

function parseBulletList(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('-') || line.startsWith('*'))
    .map((line) => line.replace(/^[-*]\s*/, '').trim())
    .filter(Boolean)
}

function parseTable(text: string): BrandPillar[] {
  const lines = text.split('\n').filter((line) => line.includes('|'))
  const pillars: BrandPillar[] = []

  for (const line of lines) {
    if (line.match(/^\|.*\|.*\|.*\|$/)) {
      const parts = line.split('|').map((p) => p.trim()).filter(Boolean)
      if (parts.length >= 3 && !parts[0].match(/^Pillar|---/)) {
        const name = parts[0].replace(/^\d+\.\s*/, '')
        const description = parts[1]
        const percentageMatch = parts[2].match(/(\d+)%/)
        const percentage = percentageMatch ? parseInt(percentageMatch[1], 10) : 0
        pillars.push({ name, description, percentage })
      }
    }
  }
  return pillars
}

function parseChannels(text: string): string[] {
  return parseBulletList(text)
}

function parseBrandAssets(text: string): string[] {
  return parseBulletList(text)
}

function parseTone(text: string): string[] {
  return text
    .split(/[,;]/)
    .map((s) => s.trim())
    .filter(Boolean)
}

/**
 * Parse full brand-profile.md markdown into structured object
 */
export function parseBrandProfileMarkdown(markdown: string): BrandProfileData {
  const clientNameMatch = markdown.match(/^# Brand Profile — (.+)$/m)
  const clientName = clientNameMatch?.[1]?.trim() ?? 'Unknown'

  const whoWeAre = extractSection(markdown, 'Who We Are')
  const audiencePersona = extractSection(markdown, 'Audience Persona')

  const toneText = extractSubSection(markdown, 'Voice & Guardrails', 'Tone of Voice')
  const dosText = extractSubSection(markdown, 'Voice & Guardrails', "Do's (Keywords & Phrases to Use)")
  const dontsText = extractSubSection(markdown, 'Voice & Guardrails', "Don'ts (Guardrails)")

  const pillarsText = extractSection(markdown, 'Content Pillars')
  const channelsText = extractSection(markdown, 'Channels (Active Platforms)')
  const brandAssetsText = extractSection(markdown, 'Brand Assets Needed')

  return {
    clientName,
    whoWeAre,
    audiencePersona,
    voice: {
      tone: parseTone(toneText),
      dos: parseBulletList(dosText),
      donts: parseBulletList(dontsText),
    },
    pillars: parseTable(pillarsText),
    channels: parseChannels(channelsText),
    brandAssets: parseBrandAssets(brandAssetsText),
  }
}

/**
 * Calculate total pillar percentage
 */
export function calculateTotalPercentage(pillars: BrandPillar[]): number {
  return pillars.reduce((sum, p) => sum + p.percentage, 0)
}

/**
 * Serialize structured object back to markdown string
 */
export function serializeBrandProfile(data: BrandProfileData): string {
  const totalPct = calculateTotalPercentage(data.pillars)
  const pctValid = totalPct === 100

  const pillarsMd = data.pillars
    .map((p, i) => `| ${i + 1}. ${p.name} | ${p.description} | ${p.percentage}% |`)
    .join('\n')

  const toneMd = data.voice.tone.join(', ')
  const dosMd = data.voice.dos.map((d) => `- ${d}`).join('\n')
  const dontsMd = data.voice.donts.map((d) => `- ${d}`).join('\n')
  const channelsMd = data.channels.map((c) => `- ${c}`).join('\n')
  const assetsMd = data.brandAssets.map((a) => `- ${a}`).join('\n')

  return `# Brand Profile — ${data.clientName}

## Who We Are
${data.whoWeAre}

## Audience Persona
${data.audiencePersona}

## Voice & Guardrails
### Tone of Voice
${toneMd}

### Do's (Keywords & Phrases to Use)
${dosMd}

### Don'ts (Guardrails)
${dontsMd}

## Content Pillars
${pctValid ? 'Exactly 4 pillars with name, description, and percentage allocation. Must sum to 100%.' : `⚠️ Total: ${totalPct}% (must be 100%)`}
| Pillar | Description | Allocation |
|--------|-------------|------------|
${pillarsMd}

## Channels (Active Platforms)
${channelsMd}

## Brand Assets Needed
${assetsMd}
`
}

/**
 * Default empty template for new clients without AI generation
 */
export function createEmptyBrandProfile(clientName: string): BrandProfileData {
  return {
    clientName,
    whoWeAre: '',
    audiencePersona: '',
    voice: {
      tone: [],
      dos: [],
      donts: [],
    },
    pillars: [
      { name: '', description: '', percentage: 40 },
      { name: '', description: '', percentage: 30 },
      { name: '', description: '', percentage: 20 },
      { name: '', description: '', percentage: 10 },
    ],
    channels: [],
    brandAssets: [],
  }
}